version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "America/Los_Angeles"
    reviewers:
      - "amalitsky"
    labels:
      - "dependencies"
      - "dependabot"
    open-pull-requests-limit: 7
    ignore:
      - dependency-name: "gzip-size"
        update-types: [ "version-update:semver-major" ]
