[build]
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/tags/"
  to = "/tags/tech/1/"

[[redirects]]
  from = "/tags/tech/"
  to = "/tags/tech/1/"

[[redirects]]
  force = true
  from = "http://en.icode.ru/"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  from = "http://en.icode.ru/backdoor/"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  force = true
  from = "https://en.icode.ru/"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  from = "https://en.icode.ru/backdoor/"
  to = "https://lab.amalitsky.com/projects/number-speller/"
