[build]
  publish = "public"
  command = "yarn build"

[[redirects]]
  from = "/tags/"
  to = "/tags/tech/1/"

[[redirects]]
  from = "/tags/tech/"
  to = "/tags/tech/1/"

[[redirects]]
  from = "/tags/cars/"
  to = "/tags/cars/1/"

[[redirects]]
  from = "/tech/"
  to = "/tags/tech/1/"

[[redirects]]
  from = "/cars/"
  to = "/tags/cars/1/"

[[redirects]]
  from = "https://labs.amalitsky.com/*"
  to = "https://lab.amalitsky.com/:splat"
  force = true

[[redirects]]
  from = "http://labs.amalitsky.com/*"
  to = "https://lab.amalitsky.com/:splat"
  force = true

[[redirects]]
  force = true
  from = "http://en.icode.ru/"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  from = "http://en.icode.ru/backdoor.html"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  from = "http://en.icode.ru/backdoor/"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  force = true
  from = "https://en.icode.ru/"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  from = "https://en.icode.ru/backdoor.html"
  to = "https://lab.amalitsky.com/projects/number-speller/"

[[redirects]]
  from = "https://en.icode.ru/backdoor/"
  to = "https://lab.amalitsky.com/projects/number-speller/"
