name: DepBot PR - After

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["PR Update"]
    types:
      - completed

concurrency:
  group: dependabot-pr-${{ github.event.action }}-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

env:
  PR_ID: ${{ github.event.workflow_run.pull_requests[0].number }}

jobs:
  remove_labels:
    name: Add label
    runs-on: ubuntu-latest
    # sender.login is needed for checks re-triggered from GH UI
    if: |
      (github.actor == 'dependabot[bot]' || github.event.sender.login == 'dependabot[bot]') &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        name: Add label
        with:
          github_token: ${{ github.token }}
          number: ${{ env.PR_ID }}
          labels: ready to merge
