# This workflow doesn't have access to secrets and has a read-only token
# Used to trigger another workflow having such access.
name: Dependabot PR Check
on:
  pull_request:
  workflow_dispatch:

jobs:
  dependabot_check:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"
