# Automatically merge Dependabot PRs which have passed all the tests
name: DB PR Automerge
on:
  workflow_run:
    workflows: ["Dependabot PR"]
    types:
      - completed

jobs:
  merge:
    name: Merge

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.4.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: false
          labels: []
          blocking_labels: do not merge
          checks_enabled: true
          method: rebase
          delete_source_branch: false
