# Automatically merge Dependabot PRs which have passed all the tests
name: DP PRs merge bot
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - labeled
      - synchronize
      - unlabeled

jobs:
  merge:
    name: Merge valid DP PRs

    runs-on: ubuntu-latest

    steps:
      - name: Mergeability check
        uses: squalrus/merge-bot@v0.4.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: false
          labels: ready to merge, dependabot
          blocking_labels: do not merge
          checks_enabled: true
          method: rebase
          delete_source_branch: false
