name: Dependabot PR Labels Check - Before

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["PR Update"]
    types:
      - requested

concurrency:
  group: dependabot-pr-${{ github.event.action }}-${{ github.event.workflow_run.head_sha }}
  cancel-in-progress: true

env:
  PR: ${{ github.event.workflow_run.pull_requests[0] }}

jobs:
  remove_labels:
    name: Remove labels
    runs-on: ubuntu-latest
    # sender.login is needed for checks re-triggered from GH UI
    if: |
      (github.actor == 'dependabot[bot]' || github.event.sender.login == 'dependabot[bot]') &&
      contains(env.PR.labels.*.name, 'ready to merge')

    steps:
      - uses: actions-ecosystem/action-remove-labels@v1.1.1
        name: Remove label
        with:
          number: ${{ env.PR.number }}
          labels: ready to merge
