name: PR Update

on:
  pull_request:
  workflow_dispatch:

env:
  PR_ID: ${{ github.event.number }}
  node-version: 16.13
  gh_action_name: pull_request
  bsr-filename: bundle-size-report.json
  bsr-filename-before: bundle-size-report-before.json
  bsr-filename-txt: bundle-size-report.txt

concurrency:
  group: pr-update-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  setup:
    name: Yarn install & cache

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        name: Set nodeJs version
        with:
          node-version: ${{ env.node-version }}

      # node_module cache helps to avoid 1 minute copying from yarn cache on every job run
      - name: node_modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}
          restore-keys: ${{ runner.os }}-${{ env.cache-name }}-

      - name: Yarn install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile

  lint:
    name: Linters

    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        name: Set nodeJs version
        with:
          node-version: ${{ env.node-version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}

      - name: lint the code
        run: yarn lint

  build:
    name: Production build

    timeout-minutes: 30

    runs-on: ubuntu-latest

    needs: setup

    env:
      staleBuildFilesFindArgs: -maxdepth 1 -type f -regextype posix-egrep -regex ".*\.(json|js|css|map|txt)$"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        name: Set nodeJs version
        with:
          node-version: ${{ env.node-version }}

      - name: Cache production build
        id: prod-build-cache
        uses: actions/cache@v3
        env:
          cache-name: prod-build
          key-1: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
          key-2: ${{ hashFiles('gatsby.config.ts','gatsby.node.ts','gatsby-ssr.tsx','src/html.tsx','src/gatsby-hooks/*.*') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ github.sha }}
          restore-keys: |-
            ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-
            ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-

      - name: Purge top level & obsolete JS, JSON, HTML and CSS files from build folder
        if: steps.prod-build-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p public
          find public ${{ env.staleBuildFilesFindArgs }}
          find public ${{ env.staleBuildFilesFindArgs }} -delete

      # skipping build on exact cache hit
      - name: Restore node_modules from cache
        if: steps.prod-build-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}

      - name: Gatsby production build
        if: steps.prod-build-cache.outputs.cache-hit != 'true'
        run: yarn build

  staging-deploy:
    name: Deploy to staging env

    runs-on: ubuntu-latest

    needs: [lint, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        name: Set nodeJs version
        with:
          node-version: ${{ env.node-version }}

      - name: Restore exact production build from cache
        uses: actions/cache@v3
        env:
          cache-name: prod-build
          key-1: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
          key-2: ${{ hashFiles('gatsby.config.ts','gatsby.node.ts','gatsby-ssr.tsx','src/html.tsx','src/gatsby-hooks/*.*') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ github.sha }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}

      - name: Staging deploy
        # no need to copy node_modules and I'm not sure why
        run: yarn deploy-netlify --alias pr$PR_ID --message $DEPLOY_MESSAGE
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOY_MESSAGE: PR${{ github.event.number }}/${{ github.sha }}

  e2e-test:
    name: E2E tests

    runs-on: ubuntu-latest

    needs: staging-deploy

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        name: Set nodeJs version
        with:
          node-version: ${{ env.node-version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}

        # figure the better way supporting all the packages
      - name: Fake yarn postinstall
        run: yarn playwright install

      - name: Run tests
        run: yarn test-e2e

  lhci:
    name: Lighthouse report

    runs-on: ubuntu-latest

    needs: staging-deploy

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Fetch base_ref HEAD to use it as Ancestor hash in LHCI
        run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}

      - uses: actions/setup-node@v2
        name: Set nodeJs version
        with:
          node-version: ${{ env.node-version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}

      - name: LHCI
        run: |
          yarn run lhci collect
          yarn run lhci upload
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}

  bundle-size-report:
    name: Bundle size report

    runs-on: ubuntu-latest

    needs: [build]

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - run: git fetch --no-tags --prune --depth=20 origin master

      - uses: actions/setup-node@v2
        name: Set nodeJs version
        with:
          node-version: ${{ env.node-version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache-name: node-modules-yarn
          cache-fingerprint: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.cache-fingerprint }}

      - name: Restore exact production build from cache
        uses: actions/cache@v3
        env:
          cache-name: prod-build
          key-1: ${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
          key-2: ${{ hashFiles('gatsby.config.ts','gatsby.node.ts','gatsby-ssr.tsx','src/html.tsx','src/gatsby-hooks/*.*') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ github.sha }}

      - name: Find the "merge-base" between target branch and last PR commit
        env:
          merge-base-cmd: git merge-base origin/${{ github.base_ref }} ${{ github.sha }}
        run: echo "merge-base-sha=$(${{ env.merge-base-cmd }})" >> $GITHUB_ENV

      - name: Restore the merge base bundle size report from cache
        id: bsr-cache-merge-base
        uses: actions/cache@v3
        with:
          path: bundle-size-report-${{ env.merge-base-sha }}.json
          key: ${{ env.merge-base-sha }}

      - name: Restore the current build bundle size report from cache
        uses: actions/cache@v3
        with:
          path: bundle-size-report-${{ github.sha }}.json
          key: ${{ github.sha }}

      - name: Bundle Size Report w comparison
        if: steps.bsr-cache-merge-base.outputs.cache-hit == 'true'
        run: yarn bsr autorun -o bundle-size-report-${{ github.sha }}.json --compare-with bundle-size-report-${{ env.merge-base-sha }}.json

      - name: Bundle Size Report wo comparison
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true'
        run: yarn bsr autorun -o bundle-size-report-${{ github.sha }}.json

      - id: read-bsr-txt-file-content
        name: Read report into the environment variable
        run: |
          body=$(cat ${{ env.bsr-filename-txt }})
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

      - name: Comment the report to PR
        uses: peter-evans/commit-comment@v2
        with:
          body: "```\n${{ steps.read-bsr-txt-file-content.outputs.body }}\n```"
