name: PRs

on:
  pull_request:
  # allows to run this workflow manually from the Actions tab
  workflow_dispatch:

  # same workflow triggered by dependabot_pr_check.yml
  workflow_run:
    workflows: ["Dependabot PR Check"]
    types:
      - completed

env:
  PR_ID: ${{ github.event.number }}

jobs:
  setup:
    runs-on: ubuntu-latest
    # don't need to run this (and dependant steps) for dependabot PRs since it will get
    # re-triggered by dependabot_pr_check workflow completion
    if: |
      ${{
        (github.event.workflow_run.event == 'pull_request' && github.actor != 'dependabot[bot]') ||
        (github.event.workflow_run.event == 'workflow_run')
      }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: install dependencies
        run: yarn install --prefer-offline

  lint:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: install deps
        run: yarn install --prefer-offline

      - name: lint the code
        run: yarn lint

  build:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-yarn
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: install deps
        run: yarn install --prefer-offline

      - name: Production build and cache it
        uses: actions/cache@v2
        env:
          cache-name: prod-build
        with:
          path: public
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: build the website
        run: yarn build

  staging-deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: restore website build from cache
        uses: actions/cache@v2
        env:
          cache-name: prod-build
        with:
          path: public
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: netlify deploy
        run: yarn deploy-netlify --alias pr$PR_ID --message $DEPLOY_MESSAGE
        env:
          NETLIFY_SITE_ID: 0f94f863-38eb-4a4b-a1c3-dd677837bd32
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOY_MESSAGE: PR${{ github.event.number }}/${{ github.sha }}
