name: PR Update

on:
  pull_request:
  workflow_dispatch:

env:
  node_version: ${{ secrets.NODE_VERSION }}
  pr_id: ${{ github.event.number }}
# last_commit_sha: ${{ github.event.pull_request.head.sha }}
  gh_action_name: pull_request
  bsr_filename_txt: bundle-size-report.txt
  stale_build_files_find_args: -maxdepth 1 -type f -regextype posix-egrep -regex ".*\.(json|js|css|map|txt)$"
  merge_base_cmd: git merge-base origin/${{ github.base_ref }} ${{ github.event.pull_request.head.sha }}

concurrency:
  group: pr-update-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  setup:
    name: Yarn install & cache
    uses: ./.github/workflows/yarn_install.yml
    secrets:
      node_version: ${{ secrets.NODE_VERSION }}

  lint:
    name: Linters

    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}

      - name: lint the code
        run: yarn lint

  build:
    name: Production build

    needs: setup

    uses: ./.github/workflows/production_build.yml
    with:
      pr_id: ${{ github.event.number }}
    secrets:
      node_version: ${{ secrets.NODE_VERSION }}

  staging-deploy:
    name: Deploy to staging env

    runs-on: ubuntu-latest

    needs: [lint, build]

    permissions:
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}

      - name: Restore exact production build from cache
        uses: actions/cache@v3
        env:
          cache_name: prod-build
          key_1: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
          key_2: ${{ hashFiles('gatsby.config.ts','gatsby.node.ts','gatsby-ssr.tsx','src/html.tsx','src/gatsby-hooks/*.*') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.key_1 }}-${{ env.key_2 }}-${{ github.sha }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}

      - name: Staging deploy
        # no need to copy node_modules and I'm not sure why
        run: yarn deploy-netlify --alias "pr-$pr_id" --message $DEPLOY_MESSAGE
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          DEPLOY_MESSAGE: PR${{ github.event.number }}/${{ github.sha }}

      - name: Add PR status completed
        uses: teamniteo/pull_request_status_action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          state: success
          pr_number: ${{ env.pr_id }}
          context: Staging Website
          description: Deployed to Netlify
          target_url: https://pr-${{ env.pr_id }}--amlab.netlify.app

  e2e-test:
    name: E2E tests

    runs-on: ubuntu-latest

    needs: staging-deploy

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}

        # figure the better way supporting all the packages
      - name: Fake yarn postinstall
        run: yarn playwright install

      - name: Run tests
        run: yarn test-e2e

  lhci:
    name: Lighthouse report

    runs-on: ubuntu-latest

    needs: staging-deploy

    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - name: Fetch base_ref HEAD to use it as Ancestor hash in LHCI
        run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}

      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}

      - name: LHCI
        run: |
          yarn run lhci collect
          yarn run lhci upload
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}

  # in case merge-base PR doesn't have bundle-size-report in cache
  # we will perform another "before changes" build and cache the report
  # to be used by bundle-size-report job below
  bundle-size-report-before:
    name: Bundle size report (before)

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - run: git fetch --no-tags --prune --depth=20 origin main

      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}

      - name: Find the "merge-base" between target branch and last PR commit
        run: echo "merge_base_sha=$(${{ env.merge_base_cmd }})" >> $GITHUB_ENV

      - name: Log merge base commit message
        run: |
          echo "### _Before_ Commit" >> $GITHUB_STEP_SUMMARY
          git show -s --format=%s ${{ env.merge_base_sha }} >> $GITHUB_STEP_SUMMARY
          echo "hash: _${{ env.merge_base_sha }}_" >> $GITHUB_STEP_SUMMARY

      # Since we assume here that "merge-base" commit is already merged in we can use its sha
      # for caching relevant BSR (unlike for the "after" report)
      - name: Restore the merge base bundle size report from cache
        id: bsr-cache-merge-base
        uses: actions/cache@v3
        with:
          path: |
            bundle-size-report-${{ env.merge_base_sha }}.json
            bundle-size-report-${{ env.merge_base_sha }}.txt
          key: ${{ env.node_version }}-${{ env.merge_base_sha }}

      - name: Merge-base checkout
        uses: actions/checkout@v3
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true'
        with:
          fetch-depth: 20
          ref: ${{ env.merge_base_sha }}

      - name: Restore node_modules from cache
        id: node-modules-cache
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache_name }}-${{ env.node_version }}-
            ${{ runner.os }}-${{ env.cache_name }}-

      - name: Yarn install
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true' &&
          steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Cache production build
        id: prod-build-cache
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        env:
          cache_name: prod-build
          key_1: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
          key_2: ${{ hashFiles('gatsby.config.ts','gatsby.node.ts','gatsby-ssr.tsx','src/html.tsx','src/gatsby-hooks/*.*') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.key_1 }}-${{ env.key_2 }}-${{ env.merge_base_sha }}
          restore-keys: |-
            ${{ runner.os }}-${{ env.cache_name }}-${{ env.key_1 }}-${{ env.key_2 }}-
            ${{ runner.os }}-${{ env.cache_name }}-${{ env.key_1 }}-

      - name: Purge top level & obsolete JS, JSON, HTML and CSS files from build folder
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true' &&
          steps.prod-build-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p public
          find public ${{ env.stale_build_files_find_args }}
          find public ${{ env.stale_build_files_find_args }} -delete

      - name: Gatsby production build
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true' &&
          steps.prod-build-cache.outputs.cache-hit != 'true'
        run: yarn build

      - name: Bundle Size Report
        if: steps.bsr-cache-merge-base.outputs.cache-hit != 'true'
        run: yarn bsr autorun -o bundle-size-report-${{ env.merge_base_sha }}.json -r bundle-size-report-${{ env.merge_base_sha }}.txt

      # using merge-base node_modules so that we don't fetch node_modules in two parallel jobs
      - name: Print before report into summary
        run: |
          echo "### _Before_ Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          cat bundle-size-report-${{ env.merge_base_sha }}.txt >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY

  bundle-size-report:
    name: Bundle size report

    runs-on: ubuntu-latest

    needs: [build, bundle-size-report-before]

    timeout-minutes: 30

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20

      - run: git fetch --no-tags --prune --depth=20 origin main

      - uses: actions/setup-node@v3
        name: Set nodeJs version
        with:
          node-version: ${{ env.node_version }}

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        env:
          cache_name: node-modules-yarn
          cache_fingerprint: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.cache_fingerprint }}

      - name: Restore exact production build from cache
        uses: actions/cache@v3
        env:
          cache_name: prod-build
          key_1: ${{ env.node_version }}-${{ hashFiles('yarn.lock') }}
          key_2: ${{ hashFiles('gatsby.config.ts','gatsby.node.ts','gatsby-ssr.tsx','src/html.tsx','src/gatsby-hooks/*.*') }}
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-${{ env.cache_name }}-${{ env.key_1 }}-${{ env.key_2 }}-${{ github.sha }}

      - name: Find the "merge-base" between target branch and last PR commit
        run: echo "merge_base_sha=$(${{ env.merge_base_cmd }})" >> $GITHUB_ENV

      - name: Restore the merge base bundle size report from cache
        id: bsr-cache-merge-base
        uses: actions/cache@v3
        with:
          path: |
            bundle-size-report-${{ env.merge_base_sha }}.json
            bundle-size-report-${{ env.merge_base_sha }}.txt
          key: ${{ env.node_version }}-${{ env.merge_base_sha }}

      - name: Bundle Size Report w comparison
        run: yarn bsr autorun -o bundle-size-report-${{ github.sha }}.json --compare-with bundle-size-report-${{ env.merge_base_sha }}.json

      - name: Bundle Size Report wo comparison to get cached and printed
        run: yarn bsr print bundle-size-report-${{ github.sha }}.json -o bundle-size-report-${{ github.sha }}.txt

      - id: read-bsr-txt-file-content
        name: Read report into the environment variable
        run: |
          echo "### _After_ Commit Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
          cat bundle-size-report-${{ github.sha }}.txt >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "~~~" >> $GITHUB_STEP_SUMMARY
